routes:
  /rss/:
    template: rss
    content_type: text/xml
  /evropa/:
    controller: channel
    template: evropa
    filter: tag:evropa

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-blog
  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: tag:blog
    data: tag.blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
